logo.image = Image("logo.png");
logo.sprite = Sprite(logo.image);
logo.x = (Window.GetX() + Window.GetWidth()) / 2 - logo.image.GetWidth() / 2;
logo.y = (Window.GetY() + Window.GetHeight()) / 2 - logo.image.GetHeight() / 2;
logo.sprite.SetPosition(logo.x, logo.y, 0);

progress_box.image = Image("progress_box.png");
progress_box.sprite = Sprite(progress_box.image);
progress_box.x = (Window.GetX() + Window.GetWidth()) / 2 - progress_box.image.GetWidth() / 2;
progress_box.y = Window.GetHeight() * 0.75;
progress_box.sprite.SetPosition(progress_box.x, progress_box.y, 0);

progress_bar.original_image = Image("progress_bar.png");
progress_bar.sprite = Sprite();
progress_bar.x = (Window.GetX() + Window.GetWidth()) / 2 - progress_bar.original_image.GetWidth() / 2;
progress_bar.y = Window.GetHeight() * 0.75 + 2;
progress_bar.sprite.SetPosition(progress_bar.x, progress_bar.y, 1);

fun progress_callback (duration, progress)
{
  if (progress_bar.original_image)
  {
    progress_bar.image = progress_bar.original_image.Scale(
      progress_bar.original_image.GetWidth() * progress,
      progress_bar.original_image.GetHeight());
    progress_bar.sprite.SetImage(progress_bar.image);
  }
}
Plymouth.SetBootProgressFunction(progress_callback);

fun quit_callback ()
{
  logo.sprite.SetOpacity(1);
}
Plymouth.SetQuitFunction(quit_callback);
